// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface ResponseModel {
    artistObj:  ArtistObj;
    artistimg:  string;
    artistname: string;
    id:         string;
    provider:   string;
    trackbg:    string;
    trackhref:  string;
    trackid:    string;
    tracklink:  string;
    trackname:  string;
    userid:     string;
}

export interface ArtistObj {
    data: Data;
    id:   number;
}

export interface Data {
    external_urls: ExternalUrls;
    followers:     Followers;
    genres:        string[];
    href:          string;
    id:            string;
    images:        Image[];
    name:          string;
    popularity:    number;
    type:          string;
    uri:           string;
}

export interface ExternalUrls {
    spotify: string;
}

export interface Followers {
    href:  null;
    total: number;
}

export interface Image {
    height: number;
    url:    string;
    width:  number;
}


export interface postData {
  artistimg: string;
  artistname: string;
  id: string;
  provider: string;
  trackbg: string;
  trackhref: string;
  trackid: string;
  tracklink: string;
  trackname: string;
  userid: string;
  artistObj: ArtistObj
}
